{% set name = "radio_beam" %}
{% set version = "0.3.6" %}

package:
  name: radio-beam
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 53e223393b7bc7dbb3525ec871046edacf8c04a17f391fac2dd76f1e6a7d86a5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:

  host:
    - python >=3.8
    - pip
    - setuptools_scm

  run:
    - python >=3.8
    - astropy
    - numpy >=1.9.0
    - scipy
    - setuptools
    - six

test:
  imports:
    - radio_beam

about:
  home: https://github.com/radio-astro-tools/radio-beam
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Tools for Beam I/O and Manipulation

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - keflavich
