{% set name = "radio_beam" %}
{% set version = "0.3.3" %}

package:
  name: radio-beam
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: e34902d91713ccab9f450b9d3e82317e292cf46a30bd42f9ad3c9a0519fcddcd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:

  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >=3.6
    - astropy
    - numpy >=1.9.0
    - six

test:
  imports:
    - radio_beam

about:
  home: https://github.com/radio-astro-tools/radio-beam
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Tools for Beam I/O and Manipulation

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - keflavich
