{% set name = "radio_beam" %}
{% set version = "0.3.8" %}

package:
  name: radio-beam
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 084feb71828edc3bb3e73c26278804baa3a83b7532eec8f03a2f7a1cfd18e770

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:

  host:
    - python >=3.8
    - pip
    - setuptools_scm

  run:
    - python >=3.8
    - astropy-base
    - numpy >=1.9.0
    - scipy
    - setuptools
    - six

test:
  imports:
    - radio_beam

about:
  home: https://github.com/radio-astro-tools/radio-beam
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Tools for Beam I/O and Manipulation

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - keflavich
