travis:
  secure:
    BINSTAR_TOKEN: bu6c8LrDT1Js58kOnGG9mJ88NX+vi8qbEZ5tXfy1hB+VqmPNp7c7Py4AxMLoJQBgpwc5L5LqmM69ntJ13uZDq5gYx58OkE+6+3cb947muGYBAR1COGPT1whZomu8wyGKInGtkXHiegnj7iJ5oQO1krNYIpDDo4txUFmk/dd5D4Ot+5ANcBjiVf9N8xqzDpZKG6Ihj8fPL6+jbC//8fBpt2Y4c2Fd6M5KzNG5UFzMo98l/JvphwQLuTRVTk2JncGe7EbI0GtOgDqsKS6ivGyIAmDm1p8fTd4j9/3RS414MJBLrpRrSv5XeQ+c36oOhB9i97JFgpr4feYlg2ku3e0zq7gEZawPJv9LVtoCNwV6dvSGBNe4N7Ijrz2VN4hDK/gBluyhF9fZ/ti8FUEhAPnq5APQFxmsjzFlcTPxPz8VkTaz0UnC/4dMquPJchhL5HAh3ybEYx3mrzsm8cLC0kyJr74GKLJBlz9OrTJqh1yPekUn9AegK+iI86kY33h1mffiRLynhCx+BH5u7JWuzPXG0q2DjXXV8Z+QiDVhSb5vuRBiH98GzTe+J3N5equoVA91/PtCOT3MglNPmeW8+bCmNj1B/T7F2MIFi5PmCX5P6DpwTY/nqC8SzqSZcnlTnjUf6XVlwW3HmOzbPRmRx7XP8zWbMWwUajSwfzk68f8EAow=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
