travis:
  secure:
    BINSTAR_TOKEN: Gys4y7BD4LGEZsiDYiwLiEWEyYznSqlYE2+GHSWQT9MlLnQF1dUkWifRdjIcsUmsDGIZkws/EG8XVE6jgHZ3NfAXRJZHVFwR5figXRA2QdPvL9Knfk3cRUTSZpvVhu4kI07QwC27AQrPl4sRT4fL+rWjquM86EB0oclpOIRCHYO9imShHHRpNX22Rnj30+eUVAo/n8CjXKJZdSwv6kLhml3gfJ93Jf3x3t6Twuo2DPXeuOPGRUIt9SLoTLWdYupbWkQvOqdJOrh0ZCGkeOkkVLRITRK9+/et6o6eDNA4Rrm8HNRIwROqwoMYJOKYRHeC9kgzEac9r6h+rP6T2m49p6GOsIyTXnNRJwt+Md8aB1gABnO1uauggzkNczbtYPl0+lCqUHmYgQKUU+P1BsPa4bR551UKIw05F0GFSXNAunh9dCZ2zCKUIqlh6cwAxu6t/VkMz6oMDlKO4ueEFjXEmeFbT82iJwrwTuSN76F+bw3+wdUKlKRyaxbqTUTi9gBge4HG5YdChZdg7HOmDSVp6ii8XlAYvRRUh6Z3krxLrnI+yIH6d0fmzMzIYEEvPTm18X6CpN/s/IQOa+fzYe+5/97OlHbOxNNcRbLPvxipe6bYtvE+zi5rc2TSFvgC3+XibqyJJjBrPWWd2NzOmT7AMVA4gTI3txgjY1VJaN+O6oA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
