travis:
  secure:
    BINSTAR_TOKEN: WBJRTQLZa3drfFghogU/3Lx6haJWLstbvVCQ0fnaBIr7MRhokzPENBmn+DBzk8tDawoUb8qVbbdS6/cvBTEXK8iFRRmQL7RPivF6szWbd/AKpyQRt46DLeyT1VYCZmwiJVh3UX+wU1bgOsWmher57dQE1e8U+OJIKQanaO9Ia3cqmqT47xtnbkyHKw9JTWuE3f/wKSln33sDnlfZRkjQYDPCdhWgb34rnfJLgBVrpYNHCWgVycA2mwbcTlyRihylMkBz/6fjFLJ/WYdEAdKBj6PRDoEtiFLYRU+ua3RHI3KsYGKpSbpoftS+GgHcFtwIjtwgcvgXWu8o5zc3b9iEqzmCjcaiL926WvggUQBUFpqKufWfRApoIxL8541pzhtp9Py6vqCSOiZ9it6ZxDYqviZIgjjvs/4uD9Jg3TNcGFTOWt+Y+s9JBRH4OKYBO4+PjSu+NM8gDHx1vT0TR0knrTkHJWqvSyXERDRIJeLngOVf+pkod4/HHpL4XJqdE/Rnir0jDcxbzDemvML7fZHoh6gWSOOmcO0A5lFBWscXFhHUL4CFM1zlp3fPjXO+51+20ofzAG/hfesv1PUEbFiy06Lf1t4KOtqCxIz0OID8n/LJgP2+q56zjoN0odo4TRnq7X0R0e+WiPsC9H+LJ4MjPi7E0i7LXAiY1d/lyqV+Jko=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
