travis:
  secure:
    BINSTAR_TOKEN: AV4AgYsBPHRiqKbIs5QeQiMFoJUNXq2zzz4v92IlRsAaJkrHknPrmt2K2Ywx+7rlKhP0o/SSnmbh+BO8vIwvCGF1F7O4IqWaykz3Kc4LTPLDrCamHyES0nA1So3MGl4dg2aev7J2YFD1+t0HxgGotWLnyvhxpib6HFp4B58YoSqFY6cNaxKBoytbs76RsYTHABJXoYsdBLYBpmbdQ6z9nvt7Wwb/BjiScxmFFnl4yI/xV8roojvYgUy0LMSXY6CCovWLIaDkl5yiC2ampKoED6wO+c+ZzW4QJF1w+pV9AYOVUIr3NJYVOkdw/IxJO8CgGe2Kh6wJJaU8Ht9Dw1au3Z1H8n56Cqt6MKQUeGyQzb4tOQNI/Lg0r55dNeI0LEtMnXVAvXDD/gkJCQmYWsZmMcca2/LDMLILW4PlrkL0gsWzURi7BuWbPxC+N9djExbs8sLT1VK7ZOvmPZuo+mDv28XIBY+R9qJz+PDZDqIkjCWU0FmXvoXKM0W4buz784cKtDL6ry2DrGuTY0gDwuBFahxzaJQEhAzTQ4MucHCGpsc5f2UFdd3c5ZQhFL/cznVSKuduioogLnuw3lCjikgRvNGRx9MplDKYeY/EEn864DsLeEA6SNzY2xn6W8oYnOQ8FjKuJVAgZj4wKgj4vS0hl3CUbmkCDTSsSMXcsd1Bu+E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
